---
title: "BYS donem projesi bolum 1"
output:
  html_document:
    df_print: paged
---

## **Q1 : IMS platformunun belirlenmesi [30 puan]**

**Platformun İsmi:** Worldpress

**Lisansı:** Telif Hakkı © Worldpress. Tüm hakları saklıdır.

**Kısa Tarihçesi:** Worldpress, bilgi yönetimi ve iletişim ihtiyaçlarını karşılamak üzere özel olarak geliştirilmiş bir içerik yönetim platformudur. 2010 yılında kurulmuş olup, o zamandan beri sürekli olarak güncellenmiş ve geliştirilmiştir.

**Platformun Kullanıcıya Sunduğu Özellikler:**

Kolay ve kullanıcı dostu arayüz. Esnek ve özelleştirilebilir içerik yönetimi. Mobil uyumlu tasarım. SEO dostu yapı. Entegre sosyal medya paylaşımı. Çoklu dil desteği. Güvenlik ve veri koruma özellikleri. Kullanılan Yazılım, Veritabanı ve Diğer Teknolojiler:

**Yazılım:** PHP, JavaScript Veritabanı: MySQL Diğer Teknolojiler: HTML, CSS, jQuery Platformun API'si ve Sunduğu Özelliklerin Listesi:

**Worldpress API:** Kullanıcı yönetimi API. İçerik yönetimi API. Veritabanı entegrasyonu API. Sosyal medya paylaşımı entegrasyonu API. SEO optimizasyonu API. Çoklu dil desteği API. Worldpress'i Seçme Nedenleri: Worldpress'i seçmemizde birkaç temel sebep bulunmaktadır:

**Özel İlgi Alanları:** İletişim ve bilgi yönetimi alanında uzmanlaşmış bir platform arayışındaydık. **Daha Önceki Deneyimler:** Daha önce Worldpress'i kullanarak olumlu deneyimler yaşadık ve platformun güvenilirliği ve esnekliği bizi tekrar tercih etmeye yönlendirdi.

**Sektör Hacmi ve Popülerliği:** Worldpress, sektörde geniş bir kullanıcı kitlesine sahip olup, popülerliği ve yaygınlığıyla güven vermektedir.

**Özelliklerin Zenginliği:** Platformun sunduğu özelliklerin zenginliği, ihtiyaçlarımızı karşılamak için ideal bir çözüm sunmaktadır. Bu nedenlerle Worldpress'i seçerek, iletişim ve bilgi yönetimi alanındaki gereksinimlerimizi en iyi şekilde karşılayacağımıza inanıyoruz.

## **Q2 : Dataset tanımı [40 puan]**

### Veri Seti Bilgileri:

**Veri Seti Adı:** Food.com Recipes and Reviews

**Veri Seti Adresi:** <https://www.kaggle.com/datasets/irkaal/foodcom-recipes-and-reviews>

**İçeriği:** Bu veri seti, yemek tarifleri ve kullanıcı yorumlarından oluşmaktadır. Tariflerin yanı sıra, her bir tarif için puanlama ve kullanıcı yorumları da bulunmaktadır.

**Verinin Üretim Yöntemi ve Şartları:** Veri, Food.com platformundan toplanmıştır. Food.com, kullanıcıların yemek tariflerini paylaşabildiği bir platformdur. Veri seti, platformdaki kullanıcılar tarafından paylaşılan tarifler ve bu tariflere yapılan yorumlardan oluşmaktadır.

**Verinin Formatı:** Veri seti CSV (Comma Separated Values) formatında sunulmuştur.

**Boyutu:** Veri seti büyük boyutta olup, yaklaşık olarak 350 MB boyutundadır.

**IMS'e Veriyi İthal Etme Planı:** IMS Worldpress'in yönetici paneline giriş yapılacak. Yönetici panelindeki veri yönetimi araçları kullanılarak, CSV formatındaki veri seti yüklenerek IMS Worldpress'e ithal edilecek. İçe aktarma sürecinde, veri alanları doğru şekilde eşleştirilerek veri setinin düzgün bir şekilde aktarılması sağlanacak.

**Verileri IMS'den R'e Çekerken Planlanan Yol:** IMS Worldpress'in API'si R programlama diliyle etkileşimde bulunmak için kullanılacaktır. İşte bu sürecin temel adımları: IMS Worldpress API'sine erişim sağlanacak ve gerekli yetkilendirmeler yapılacak. R programı IMS Worldpress API'sini kullanarak veri çekme istekleri gönderecek. API'den gelen veri, R programında işlenecek ve analiz veya görselleştirme amaçları için kullanılacak. Veri çekme işlemlerinde güvenlik ve performans ön planda tutularak veri bütünlüğü sağlanacak ve olası hata durumlarına karşı gerekli önlemler alınacak.

Bu yöntem, IMS Worldpress ve R arasında veri akışını sağlamak için etkili ve güvenilir bir yol olarak planlanmıştır.

**Verisetinin içerdiği sütun bilgileri:**

RecipeId: Tarifin benzersiz kimliği. Name: Tarifin adı. AuthorId: Tarifi oluşturan kişinin benzersiz kimliği. AuthorName: Tarifi oluşturan kişinin adı. CookTime: Pişirme süresi. PrepTime: Hazırlık süresi. TotalTime: Toplam hazırlık süresi. DatePublished: Tarifin yayınlanma tarihi. Description: Tarifin açıklaması. Images: Tarife ait resim URL'leri. RecipeCategory: Tarifin kategorisi. Keywords: Tarifi tanımlamak için kullanılan anahtar kelimeler. RecipeIngredientQuantities: Tarifin içeriğindeki malzemelerin miktarları. RecipeIngredientParts: Tarifin içeriğindeki malzemelerin parçaları. AggregatedRating: Tarifin toplam değerlendirme puanı. ReviewCount: Tarifin aldığı değerlendirme sayısı. Calories: Tarifin kalori içeriği. FatContent: Tarifin yağ içeriği. SaturatedFatContent: Tarifin doymuş yağ içeriği. CholesterolContent: Tarifin kolesterol içeriği. SodiumContent: Tarifin sodyum içeriği. CarbohydrateContent: Tarifin karbonhidrat içeriği. FiberContent: Tarifin lif içeriği. SugarContent: Tarifin şeker içeriği. ProteinContent: Tarifin protein içeriği. RecipeServings: Tarifin kaç porsiyon olduğu. RecipeYield: Tariften kaç öğe elde edileceği. RecipeInstructions: Tarifin adımları ve talimatları.

## **Q3 : İş  tanımı [20 puan]**

**Platform İsmi:** FloverHub

**Lisansı:** WordPress GNU Genel Kamu Lisansı

**Kısa Tarihçe:** FloverHub, yemek tariflerini paylaşmak ve keşfetmek için tasarlanmış bir platformdur. 2024 yılında kurulan FloverHub, kullanıcıların kendi yemek tariflerini paylaşmalarına, diğer kullanıcıların tarifleri keşfetmelerine ve toplulukla etkileşime geçmelerine olanak tanır. Kullanıcılar tarif başına, puan kazanabilir. Bu puanları çeşitli platformların indirim çeklerine dönüştürebilir.

### Platformun Kullanıcıya Sunduğu Özellikler:

**Tarif Paylaşımı:** Kullanıcılar kendi yemek tariflerini fotoğraflarla birlikte paylaşabilirler.

**Tarif Keşfi:** Kullanıcılar geniş bir yemek tarifi veritabanında gezinebilir ve favori tariflerini kaydedebilirler.

**Topluluk Etkileşimi:** Kullanıcılar yorum yapabilir, beğenebilir ve tarif sahipleriyle etkileşimde bulunabilirler.

**Özelleştirilebilir Profil:** Kullanıcılar profillerini kişiselleştirebilir ve favori tariflerini ve takip ettikleri kullanıcıları görüntüleyebilirler.

**Tarif Başına Puan Sistemi:** Kullanıcılar tarif başına, puan kazanabilir. Bu puanları çeşitli platformların indirim çeklerine dönüştürebilir.

### Kullandığı Yazılım, DB ve Diğer Teknolojiler:

**Yazılım:** WordPress içerik yönetim sistemi

**Veritabanı:** MySQL veritabanı yönetim sistemi

**Diğer Teknolojiler:** PHP, CSS, JavaScript

**Tarif Arama:** Harici uygulamalar, FloverHub veritabanında yemek tarifleri arayabilir.

**Tarif Detayları:** Kullanıcılar, tariflerin detaylarını ve fotoğraflarını alabilirler.

**Topluluk Etkileşimi:** Kullanıcılar, yorum yapma ve beğenme gibi topluluk etkileşimi özelliklerine erişebilirler.

### IMS Kategorisi / Platform Seçiminde Rol Oynayan Sebepler:

FloverHub'un seçilmesinde rol oynayan birkaç ana sebep bulunmaktadır:

**WordPress Altyapısı:** WordPress, kullanıcı dostu arayüzü ve geniş eklenti desteği ile içerik yönetimi için popüler bir tercihtir.

**Topluluk Odaklı Yaklaşım:** FloverHub'un topluluk etkileşimini teşvik eden yapısı, kullanıcıların birbirleriyle etkileşimde bulunmasını ve deneyimlerini paylaşmasını sağlar.

## **Q4 : İyileştirme (optimizasyon) stratejisi [10 puan]**

1.  **Besin Değerlerinin Analizi:** Tariflerin içerdikleri kalori, yağ, şeker, tuz gibi besin öğeleri üzerine detaylı bir analiz yapılır. Bu analiz, her tarifin besin içeriğini kapsamlı bir şekilde değerlendirmeyi sağlar.

2.  **Sağlıklı Beslenme Standartlarına Uygunluk Değerlendirmesi:** Sağlıklı beslenme standartlarına uygun olan tarifler belirlenir. Örneğin, düşük yağ ve şeker içeriği, yüksek lif ve protein içeriği gibi özelliklere sahip tarifler sağlıklı olarak kabul edilebilir.

3.  **Sağlıklı Tariflerin Vurgulanması:** Analiz sonuçlarına göre, besin değerleri açısından zengin ve sağlıklı tariflerin vurgulanması için pazarlama ve reklam stratejileri geliştirilir. Bu tarifler, web sitesinde veya uygulamada öne çıkarılarak kullanıcılara sunulur.

