services:
  wordpress:
    image: wordpress:6.5.3-php8.2-apache
    restart: always
    ports:
      - 80:80
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mariadb:10.4.32
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ''
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 81:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ''
